# Episode 1 : Variables 

In [2]:
3+5*4

23

In [3]:
weight_kg=60

In [5]:
0weight_kg

SyntaxError: invalid decimal literal (1058816760.py, line 1)

In [6]:
weight_kg_50=100

In [9]:
type(weight_kg)

int

In [10]:
weight_kg=60.3

In [11]:
type(weight_kg)

float

In [12]:
patient_id="001"

In [14]:
type(patient_id)

str

In [15]:
weight_lb=2.2*weight_kg 

In [17]:
weight_lb

132.66

In [16]:
patient_id="inflam_"+patient_id

In [19]:
patient_id

'inflam_001'

In [20]:
### built-in functions

print(weight_lb)

132.66


In [21]:
print(patient_id)

inflam_001


In [22]:
print(patient_id,"weight in kilograms:",weight_kg)

inflam_001 weight in kilograms: 60.3


In [25]:
print(type(patient_id),type(weight_kg)) # display type of variables 

<class 'str'> <class 'float'>


# Episode 2 : Lists 

In [26]:
odds=[1,3,5,7]

In [28]:
odds[0]# the first element of the list

1

In [29]:
odds[2]# the third element of the list


5

In [38]:
odds[-2:]

[5, 7]

In [39]:
veg=[["lettuce","tomato","peppers"],["cucumber"],["cilantro","zucchini"]]

In [44]:
veg[-2:]

[['cucumber'], ['cilantro', 'zucchini']]

In [45]:
names=["Curie","Darwing","Turing"]

In [46]:
print("names are originally",names)

names are originally ['Curie', 'Darwing', 'Turing']


In [47]:
names[1]="Darwin"

In [48]:
print("final values of names",names)

final values of names ['Curie', 'Darwin', 'Turing']


In [49]:
name="Darwin"
name[0]="d"

TypeError: 'str' object does not support item assignment

In [51]:
odds.append(9)
print("odds after adding a value",odds)

odds after adding a value [1, 3, 5, 7, 9]


In [53]:
removed_element=odds.pop(0)
print("odds after removing an element",odds)
print("removed_element",removed_element)

odds after removing an element [3, 5, 7, 9]
removed_element 1


# Episode 3 : Analyze data 

In [54]:
import numpy

In [56]:
numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [57]:
data=numpy.loadtxt(fname="data/inflammation-01.csv",delimiter=",")

In [58]:
type(data)

numpy.ndarray

In [59]:
data.shape

(60, 40)

In [60]:
print("the first value in data",data[0,0])

the first value in data 0.0


In [63]:
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [65]:
data[:4,:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [66]:
data[:3,36:]

array([[2., 3., 0., 0.],
       [1., 1., 0., 1.],
       [2., 2., 1., 1.]])

In [67]:
print("The mean of data",numpy.mean(data))

The mean of data 6.14875


In [68]:
maxval,minval,stdval=numpy.amax(data),numpy.amin(data),numpy.std(data)

In [70]:
print("maximum inflammation",maxval)
print("minimum inflammation",minval)
print("standard deviation",stdval)

maximum inflammation 20.0
minimum inflammation 0.0
standard deviation 4.613833197118566


In [72]:
patient_0=data[0,:]
print("the maximum inflammation for patient 0:",numpy.amax(patient_0))

the maximum inflammation for patient 0: 18.0


In [75]:
mean_per_day=numpy.mean(data,axis=0)

In [76]:
mean_per_day.shape

(40,)

In [77]:
mean_per_patient=numpy.mean(data,axis=1)
mean_per_patient.shape

(60,)